version: "3"

services:
 tekskil_server_case_ui:
  image: tekskil_server_case_ui
  network_mode: "host"
  privileged: true
  volumes:
   #- shared_data:/app/data
   - ./tcs_ui/case_ui:/app #used for development only to keep python code live
   - /home/main/Documents/tcs_ui_pipe:/app/compipe
  restart: on-failure

 #disco-scanner:
  #image: disco-scanner
  #network_mode: "host"
  #volumes:
   #- shared_data:/app/data
  #restart: on-failure

#volumes:
 #shared_data:

